version: "2.0"
services:
  mysql:
    image: mysql:5.7
    environment: 
      - "MYSQL_ROOT_PASSWORD=admin"
    networks: 
      - "prestashop-net"
  prestashop:
    image: prestashop/prestashop
    volumes:
      - "./www/html:/var/www/html"
    environment:
      - "DB_SERVER=mysql"
    ports:
      - "80:80"
    networks:
      - "prestashop-net"

networks:
  prestashop-net: 


  