<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAdmq8fs\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAdmq8fs/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAdmq8fs.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAdmq8fs\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAdmq8fs\appProdProjectContainer(array(
    'container.build_hash' => 'Admq8fs',
    'container.build_id' => 'cf5932ff',
    'container.build_time' => 1542499781,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAdmq8fs');
